# Generated by Django 4.2.1 on 2024-01-03 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_alter_studentuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobdiscription', models.TextField()),
                ('jobtitle', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('companylogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('vacancies', models.TextField()),
                ('experience', models.TextField()),
                ('jobmode', models.TextField()),
                ('minsalary', models.TextField()),
                ('maxsalary', models.TextField()),
                ('applybefor', models.TextField()),
                ('qualification', models.TextField()),
                ('skill', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
