# Generated by Django 4.2.1 on 2024-01-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='location',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
