# Generated by Django 4.2.1 on 2024-01-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_clinteragister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinteragister',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clinteragister',
            name='cellphone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clinteragister',
            name='companydescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clinteragister',
            name='companylogo',
            field=models.FileField(null=True, upload_to='company_logo_clinte'),
        ),
        migrations.AlterField(
            model_name='clinteragister',
            name='companywebsite',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clinteragister',
            name='landlinephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clinteragister',
            name='noofemployees',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
