# Generated by Django 4.2.1 on 2024-01-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_clinteragister_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinteragister',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
