# Generated by Django 4.2.1 on 2024-01-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_userpost_address_userpost_cellphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='companydescription',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='companywebsite',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='landlinephone',
        ),
    ]
