# Generated by Django 4.2.1 on 2024-01-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_userpost_address_remove_userpost_cellphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='companylogo',
        ),
    ]
