# Generated by Django 4.2.1 on 2024-01-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_userpost_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='recruiter_resume')),
                ('recruituser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruter', to='job.userpost')),
            ],
        ),
    ]
