# Generated by Django 4.2.1 on 2024-01-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_recruitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='recruituser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruter', to='job.userpost'),
        ),
    ]
