# Generated by Django 4.2.1 on 2024-02-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpostreplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatename', models.CharField(max_length=100)),
                ('jobtitle', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.userpost')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
