# Generated by Django 4.2.1 on 2024-02-05 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_userpostreplay_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostreplay',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobreplay', to='job.userpost'),
        ),
    ]
