# Generated by Django 4.2.1 on 2024-02-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_userpostreplay_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostreplay',
            name='jobtitle',
        ),
        migrations.AddField(
            model_name='userpostreplay',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpostreplay',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpostreplay',
            name='resume',
            field=models.FileField(null=True, upload_to='jobapply'),
        ),
        migrations.AlterField(
            model_name='userpostreplay',
            name='candidatename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
