# Generated by Django 4.2.1 on 2024-02-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_remove_userpostreplay_jobtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostreplay',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreplay', to='job.userpost'),
        ),
    ]
