# Generated by Django 4.2.1 on 2024-02-06 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0020_alter_userpostreplay_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostreplay',
            name='jobtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpostreplay',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpostreplay',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreplay', to=settings.AUTH_USER_MODEL),
        ),
    ]
