# Generated by Django 5.1.2 on 2024-11-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_userpostreplay_jobtitle_alter_userpostreplay_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(max_length=200)),
            ],
        ),
    ]
