# Generated by Django 5.1.2 on 2024-11-07 10:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_dec',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.TextField(max_length=100),
        ),
    ]
